package com.mstarc.wearablemms.database.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.mstarc.wearablemms.database.bean.JunkMMS;

import com.mstarc.wearablemms.database.greendao.JunkMMSDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig junkMMSDaoConfig;

    private final JunkMMSDao junkMMSDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        junkMMSDaoConfig = daoConfigMap.get(JunkMMSDao.class).clone();
        junkMMSDaoConfig.initIdentityScope(type);

        junkMMSDao = new JunkMMSDao(junkMMSDaoConfig, this);

        registerDao(JunkMMS.class, junkMMSDao);
    }
    
    public void clear() {
        junkMMSDaoConfig.clearIdentityScope();
    }

    public JunkMMSDao getJunkMMSDao() {
        return junkMMSDao;
    }

}
